### ISSUE TITLE
Compilation error with gcc 10.1.0

### ISSUE THREAD

**Issue by videlec** [flatsurf/exact-real#95] opened 2020-07-28 10:02 UTC
```
libtool: compile:  g++ -std=gnu++11 -std=gnu++17 -DHAVE_CONFIG_H -I. -I../exact-real -isystem ./external/cereal/include -g3 -march=native -mtune=native -fmax-errors=1 -Og -O2 -flto -I/opt/sage/local/include -L/opt/sage/local/lib -Wall -Wextra -pedantic -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wno-sign-compare -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wsign-promo -Wstrict-null-sentinel -Wundef -fdiagnostics-show-option -Wconversion -Wshadow-compatible-local -fdiagnostics-color=always -Wno-deprecated -Wno-deprecated-declarations -MT arf.lo -MD -MP -MF .deps/arf.Tpo -c arf.cc  -fPIC -DPIC -o .libs/arf.o
In file included from ../../../../../../../opt/sage/local/include/arf.h:26,
                 from ../exact-real/arf.hpp:26,
                 from arf.cc:21:
../../../../../../../opt/sage/local/include/flint/flint.h:160:5: warning: "__STDC_VERSION__" is not defined, evaluates to 0 [-Wundef]
  160 | #if __STDC_VERSION__ >= 201112L
      |     ^~~~~~~~~~~~~~~~
In file included from ../../../../../../../opt/sage/local/include/fmpr.h:30,
                 from ../../../../../../../opt/sage/local/include/arf.h:27,
                 from ../exact-real/arf.hpp:26,
                 from arf.cc:21:
../../../../../../../opt/sage/local/include/fmpz_extras.h: In function 'void fmpz_set_mpn_large(fmpz*, mp_srcptr, mp_size_t, int)':
../../../../../../../opt/sage/local/include/fmpz_extras.h:143:29: warning: conversion from 'mp_size_t' {aka 'long int'} to 'int' may change value [-Wconversion]
  143 |     zz->_mp_size = negative ? -n : n;
      |                    ~~~~~~~~~^~~~~~~~
In file included from ../../../../../../../opt/sage/local/include/arf.h:27,
                 from ../exact-real/arf.hpp:26,
                 from arf.cc:21:
../../../../../../../opt/sage/local/include/fmpr.h: At global scope:
../../../../../../../opt/sage/local/include/fmpr.h:58:8: warning: redundant redeclaration of 'double arb_test_multiplier()' in same scope [-Wredundant-decls]
   58 | double arb_test_multiplier(void);
      |        ^~~~~~~~~~~~~~~~~~~
In file included from ../../../../../../../opt/sage/local/include/fmpr.h:30,
                 from ../../../../../../../opt/sage/local/include/arf.h:27,
                 from ../exact-real/arf.hpp:26,
                 from arf.cc:21:
../../../../../../../opt/sage/local/include/fmpz_extras.h:34:8: note: previous declaration of 'double arb_test_multiplier()'
   34 | double arb_test_multiplier(void);
      |        ^~~~~~~~~~~~~~~~~~~
In file included from ../../../../../../../opt/sage/local/include/flint/flint.h:33,
                 from ../../../../../../../opt/sage/local/include/arf.h:26,
                 from ../exact-real/arf.hpp:26,
                 from arf.cc:21:
../../../../../../../opt/sage/local/include/arf.h: In function 'void arf_init_set_ui(arf_struct*, mp_limb_t)':
../../../../../../../opt/sage/local/include/flint/longlong.h:109:23: warning: conversion from 'mp_limb_t' {aka 'long unsigned int'} to 'unsigned int' may change value [-Wconversion]
  109 |     (count) = __cbtmp ^ (mp_limb_t) 63;                               \
      |               ~~~~~~~~^~~~~~~~~~~~~~~~
../../../../../../../opt/sage/local/include/arf.h:435:9: note: in expansion of macro 'count_leading_zeros'
  435 |         count_leading_zeros(c, v);
      |         ^~~~~~~~~~~~~~~~~~~
../../../../../../../opt/sage/local/include/arf.h: In function 'void arf_set_ui(arf_struct*, mp_limb_t)':
../../../../../../../opt/sage/local/include/flint/longlong.h:109:23: warning: conversion from 'mp_limb_t' {aka 'long unsigned int'} to 'unsigned int' may change value [-Wconversion]
  109 |     (count) = __cbtmp ^ (mp_limb_t) 63;                               \
      |               ~~~~~~~~^~~~~~~~~~~~~~~~
../../../../../../../opt/sage/local/include/arf.h:467:9: note: in expansion of macro 'count_leading_zeros'
  467 |         count_leading_zeros(c, v);
      |         ^~~~~~~~~~~~~~~~~~~
In file included from ../exact-real/yap/../exact-real.hpp:30,
                 from ../exact-real/yap/../forward.hpp:31,
                 from ../exact-real/yap/terminal.hpp:24,
                 from ../exact-real/arf.hpp:31,
                 from arf.cc:21:
../../../../../../../opt/sage/local/include/arb.h: At global scope:
../../../../../../../opt/sage/local/include/arb.h:38:8: warning: redundant redeclaration of 'double arb_test_multiplier()' in same scope [-Wredundant-decls]
   38 | double arb_test_multiplier(void);
      |        ^~~~~~~~~~~~~~~~~~~
In file included from ../../../../../../../opt/sage/local/include/arf.h:27,
                 from ../exact-real/arf.hpp:26,
                 from arf.cc:21:
../../../../../../../opt/sage/local/include/fmpr.h:58:8: note: previous declaration of 'double arb_test_multiplier()'
   58 | double arb_test_multiplier(void);
      |        ^~~~~~~~~~~~~~~~~~~
In file included from ../exact-real/yap/../exact-real.hpp:30,
                 from ../exact-real/yap/../forward.hpp:31,
                 from ../exact-real/yap/terminal.hpp:24,
                 from ../exact-real/arf.hpp:31,
                 from arf.cc:21:
../../../../../../../opt/sage/local/include/arb.h: In function 'double _arb_vec_estimate_allocated_bytes(mp_limb_signed_t, mp_limb_signed_t)':
../../../../../../../opt/sage/local/include/arb.h:1012:12: warning: conversion from 'mp_limb_signed_t' {aka 'long int'} to 'double' may change value [-Wconversion]
 1012 |     size = len * (double) sizeof(arb_struct);
      |            ^~~
../../../../../../../opt/sage/local/include/arb.h:1015:17: warning: conversion from 'mp_limb_signed_t' {aka 'long int'} to 'double' may change value [-Wconversion]
 1015 |         size += len * (double) ((prec + FLINT_BITS - 1) / FLINT_BITS) * sizeof(mp_limb_t);
      |                 ^~~
arf.cc: In function 'std::ostream& exactreal::operator<<(std::ostream&, const exactreal::Arf&)':
arf.cc:190:15: error: no match for 'operator<<' (operand types are 'std::ostream' {aka 'std::basic_ostream<char>'} and 'int')
  190 |     return os << 0;
      |            ~~ ^~ ~
      |            |     |
      |            |     int
      |            std::ostream {aka std::basic_ostream<char>}
arf.cc:188:10: note: candidate: 'std::ostream& exactreal::operator<<(std::ostream&, const exactreal::Arf&)'
  188 | ostream& operator<<(ostream& os, const Arf& self) {
      |          ^~~~~~~~
arf.cc:188:45: note:   no known conversion for argument 2 from 'int' to 'const exactreal::Arf&'
  188 | ostream& operator<<(ostream& os, const Arf& self) {
      |                                  ~~~~~~~~~~~^~~~
In file included from /usr/include/c++/10.1.0/memory:84,
                 from ../exact-real/arf.hpp:24,
                 from arf.cc:21:
/usr/include/c++/10.1.0/bits/shared_ptr.h:69:5: note: candidate: 'template<class _Ch, class _Tr, class _Tp, __gnu_cxx::_Lock_policy _Lp> std::basic_ostream<_Ch, _Tr>& std::operator<<(std::basic_ostream<_Ch, _Tr>&, const std::__shared_ptr<_Tp, _Lp>&)'
   69 |     operator<<(std::basic_ostream<_Ch, _Tr>& __os,
      |     ^~~~~~~~
/usr/include/c++/10.1.0/bits/shared_ptr.h:69:5: note:   template argument deduction/substitution failed:
arf.cc:190:18: note:   mismatched types 'const std::__shared_ptr<_Tp, _Lp>' and 'int'
  190 |     return os << 0;
      |                  ^
In file included from /usr/include/c++/10.1.0/bits/basic_string.h:48,
                 from /usr/include/c++/10.1.0/string:55,
                 from /usr/include/gmpxx.h:41,
                 from ../exact-real/arf.hpp:28,
                 from arf.cc:21:
/usr/include/c++/10.1.0/string_view:622:5: note: candidate: 'template<class _CharT, class _Traits> std::basic_ostream<_Ch, _Tr>& std::operator<<(std::basic_ostream<_Ch, _Tr>&, std::basic_string_view<_CharT, _Traits>)'
  622 |     operator<<(basic_ostream<_CharT, _Traits>& __os,
      |     ^~~~~~~~
/usr/include/c++/10.1.0/string_view:622:5: note:   template argument deduction/substitution failed:
arf.cc:190:18: note:   mismatched types 'std::basic_string_view<_CharT, _Traits>' and 'int'
  190 |     return os << 0;
      |                  ^
In file included from /usr/include/c++/10.1.0/string:55,
                 from /usr/include/gmpxx.h:41,
                 from ../exact-real/arf.hpp:28,
                 from arf.cc:21:
/usr/include/c++/10.1.0/bits/basic_string.h:6458:5: note: candidate: 'template<class _CharT, class _Traits, class _Alloc> std::basic_ostream<_Ch, _Tr>& std::operator<<(std::basic_ostream<_Ch, _Tr>&, const std::__cxx11::basic_string<_CharT, _Traits, _Allocator>&)'
 6458 |     operator<<(basic_ostream<_CharT, _Traits>& __os,
      |     ^~~~~~~~
/usr/include/c++/10.1.0/bits/basic_string.h:6458:5: note:   template argument deduction/substitution failed:
arf.cc:190:18: note:   mismatched types 'const std::__cxx11::basic_string<_CharT, _Traits, _Allocator>' and 'int'
  190 |     return os << 0;
      |                  ^
In file included from /usr/include/boost/operators.hpp:97,
                 from ../exact-real/arf.hpp:29,
                 from arf.cc:21:
/usr/include/c++/10.1.0/cstddef:125:5: note: candidate: 'template<class _IntegerType> constexpr std::__byte_op_t<_IntegerType> std::operator<<(std::byte, _IntegerType)'
  125 |     operator<<(byte __b, _IntegerType __shift) noexcept
      |     ^~~~~~~~
/usr/include/c++/10.1.0/cstddef:125:5: note:   template argument deduction/substitution failed:
arf.cc:190:12: note:   cannot convert 'os' (type 'std::ostream' {aka 'std::basic_ostream<char>'}) to type 'std::byte'
  190 |     return os << 0;
      |            ^~
In file included from /usr/include/c++/10.1.0/bits/ios_base.h:46,
                 from /usr/include/c++/10.1.0/streambuf:41,
                 from /usr/include/c++/10.1.0/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/10.1.0/iterator:66,
                 from /usr/include/boost/operators.hpp:98,
                 from ../exact-real/arf.hpp:29,
                 from arf.cc:21:
/usr/include/c++/10.1.0/system_error:262:5: note: candidate: 'template<class _CharT, class _Traits> std::basic_ostream<_Ch, _Tr>& std::operator<<(std::basic_ostream<_Ch, _Tr>&, const std::error_code&)'
  262 |     operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __e)
      |     ^~~~~~~~
/usr/include/c++/10.1.0/system_error:262:5: note:   template argument deduction/substitution failed:
arf.cc:190:18: note:   cannot convert '0' (type 'int') to type 'const std::error_code&'
  190 |     return os << 0;
      |                  ^
compilation terminated due to -fmax-errors=1.
```

**Comment by saraedum** [comment] 2020-09-04 13:04
Duplicate of #106.

**Closed by saraedum** 2020-09-04 13:04 UTC
